services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: eshop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.springboot.rule=Host(`anthonyx82.ddns.net`) && PathPrefix(`/springboot`)"
      - "traefik.http.routers.springboot.entrypoints=websecure"
      - "traefik.http.routers.springboot.tls.certresolver=myresolver"
      - "traefik.http.middlewares.springboot-stripprefix.stripprefix.prefixes=/springboot"
      - "traefik.http.routers.springboot.middlewares=springboot-stripprefix"

networks:
  web:
    external: true

volumes:
  mysql_data: