services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - eshop_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.springboot.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH_PREFIX}`)"
      - "traefik.http.routers.springboot.entrypoints=websecure"
      - "traefik.http.routers.springboot.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

networks:
  web:
    external: true

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /raid0/ftpsv/ftp/Docker/volumes/eshop_mysql_data
      o: bind
